"""API contract tests for the hybrid search mode (POST /v1/search)."""

from __future__ import annotations

import pytest
from fastapi.testclient import TestClient

from services.api import main as api_main
from shared.schemas import SearchRequest


@pytest.fixture()
def client() -> TestClient:
    return TestClient(api_main.app)


def test_search_request_accepts_hybrid_mode():
    req = SearchRequest(query="platinum", mode="hybrid")
    assert req.mode == "hybrid"


def test_search_request_rejects_unknown_mode():
    with pytest.raises(Exception):
        SearchRequest(query="platinum", mode="vector")


def test_search_request_still_accepts_legacy_modes():
    assert SearchRequest(query="q", mode="ai").mode == "ai"
    assert SearchRequest(query="q", mode="traditional").mode == "traditional"


def test_hybrid_endpoint_returns_rag_contract(client: TestClient):
    """End-to-end through the app with the real singleton service (Hybrid RAG).

    Requires the local Chroma collection + BM25 pickle (repo data ships both);
    the service degrades to dense-only if BM25 is missing. The grounded answer
    is generated by the local Ollama LLM when available; when it is down the
    request still returns the ranked pages (fail-open), so only the page-list
    side of the contract is asserted unconditionally.
    """
    response = client.post(
        "/v1/search",
        json={"query": "platinum card", "language": "auto", "mode": "hybrid", "limit": 3},
    )
    if response.status_code != 200:
        pytest.skip("live index unavailable in this environment")
    payload = response.json()
    assert payload["mode"] == "hybrid"
    assert isinstance(payload["results"], list)
    assert payload["total_results"] >= len(payload["results"])
    retrieved_urls = {item["url"] for item in payload["results"]}
    if payload["answer"]:
        # Grounded citations must point at retrieved pages only.
        for citation in payload["citations"]:
            assert citation["url"] in retrieved_urls
        assert payload["answered"] is True
        assert 0.0 < payload["confidence"] <= 1.0
    else:
        # LLM down/refused → pages-only, never a failed request.
        assert payload["answered"] is False or payload["abstention_reason"]
    for item in payload["results"][:3]:
        assert item["url"].startswith(("http://", "https://"))
        assert item["language"] in {"ar", "en"}
        assert 0.0 < item["score"] <= 1.0


def test_traditional_mode_contract_unchanged(client: TestClient):
    """Regression guard: traditional contract is untouched by the hybrid branch."""
    response = client.post(
        "/v1/search",
        json={"query": "platinum", "language": "en", "mode": "traditional", "limit": 3},
    )
    if response.status_code != 200:
        pytest.skip("live index unavailable in this environment")
    payload = response.json()
    assert payload["mode"] == "traditional"
    assert payload["answer"] is None
    assert isinstance(payload["results"], list)
